### ISSUE TITLE
why i cant visit my https website by crosswalk-webview-arm-23

### ISSUE THREAD

**Issue by Jackie2016** [crosswalk-project/crosswalk#3996]
why i cant visit my https website by crosswalk-webview-arm-23.
when i visit my website by https,i got request is denied for insecurity，net:err_unsecure_reponse.
my ssl certification is ok in chrome,firefox and so on.
in those browser shows my certification msg as below
the website had be verified by Symantec Basic DV SSL CA-G2

**Comment by rakuco** [comment]
The same question was also asked in both of our mailing lists. Closing.

**Comment by rupebac** [comment]
instead of closing the ticket, it would be nice that you point out to the exact answer, specially now that there is no support and the mail list does not work.
