### ISSUE TITLE
Clean checkout - build failed

### ISSUE THREAD

**Issue by frankvdb7** [crosswalk-project/crosswalk#3997]
I've checked out the latest Crosswalk from origin/master and ran 
> gn gen out/Default
> ninja -C out/Default xwalk_core_library__aar

I get the following compilation error:

> ninja: Entering directory 'out/Default'
> [1812/17278] ACTION //xwalk/runtime/android/core_internal:...k_core_reflection_layer_gen(//build/toolchain/android:arm)
> value callback with Boolean
> value callback with XWalkViewInternal
> value callback with Uri
> value callback with String
> Generating bridge and wrapper code for ClientCertRequestHandlerInternal.
> Generating bridge and wrapper code for ClientCertRequestInternal.
> Generating bridge and wrapper code for CustomViewCallbackHandlerInternal.
> Generating bridge and wrapper code for CustomViewCallbackInternal.
> Generating bridge and wrapper code for XWalkCookieManagerInternal.
> Generating bridge and wrapper code for XWalkDownloadListenerInternal.
> Generating bridge and wrapper code for XWalkExtensionInternal.
> Generating bridge and wrapper code for XWalkExternalExtensionManagerInternal.
> Generating bridge and wrapper code for XWalkFindListenerInternal.
> Generating bridge and wrapper code for XWalkGetBitmapCallbackInternal.
> Generating bridge and wrapper code for XWalkHttpAuthHandlerInternal.
> Generating bridge and wrapper code for XWalkHttpAuthInternal.
> Generating bridge and wrapper code for XWalkJavascriptResultHandlerInternal.
> Generating bridge and wrapper code for XWalkJavascriptResultInternal.
> Generating bridge and wrapper code for XWalkNativeExtensionLoaderInternal.
> Generating bridge and wrapper code for XWalkNavigationHistoryInternal.
> Generating bridge and wrapper code for XWalkNavigationItemInternal.
> Generating bridge and wrapper code for XWalkPreferencesInternal.
> Generating bridge and wrapper code for XWalkResourceClientInternal.
> Generating bridge and wrapper code for XWalkSettingsInternal.
> Generating bridge and wrapper code for XWalkUIClientInternal.
> Generating bridge and wrapper code for XWalkHitTestResultInternal.
> Generating bridge and wrapper code for XWalkViewInternal.
> Generating bridge and wrapper code for XWalkViewDatabaseInternal.
> Generating bridge and wrapper code for XWalkWebResourceRequestHandlerInternal.
> Generating bridge and wrapper code for XWalkWebResourceRequestInternal.
> Generating bridge and wrapper code for XWalkWebResourceResponseInternal.
> [1930/17278] ACTION //content/public/android:common_aidl(//build/toolchain/android:arm)
> FAILED: gen/content/public/android/common_aidl.d gen/content/public/android/common_aidl.srcjar
> python ../../build/android/gyp/aidl.py --depfile gen/content/public/android/common_aidl.d --aidl-path ../../third_party/android_tools/sdk/build-tools/23.0.1/aidl --imports=\[\"../../third_party/android_tools/sdk/platforms/android-23/framework.aidl\",\ \"../../content/public/android/java/src/org/chromium/content/common/common.aidl\"\] --srcjar gen/content/public/android/common_aidl.srcjar --includes=\[\"../../content/public/android/java/src\"\] ../../content/public/android/java/src/org/chromium/content/common/IChildProcessCallback.aidl ../../content/public/android/java/src/org/chromium/content/common/IChildProcessService.aidl
> Traceback (most recent call last):
>   File "../../build/android/gyp/aidl.py", line 62, in <module>
>     sys.exit(main(sys.argv))
>   File "../../build/android/gyp/aidl.py", line 45, in main
>     build_utils.CheckOutput(aidl_cmd)
>   File "/mnt/f/Crosswalk/src/build/android/gyp/util/build_utils.py", line 164, in CheckOutput
>     stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 8] Exec format error
> [1934/17278] ACTION //components/web_contents_delegate_and...esources__process_resources(//build/toolchain/android:arm)
> FAILED: gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources__process_resources.d gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.resources.zip gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.srcjar gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources_R.txt
> python ../../build/android/gyp/process_resources.py --depfile gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources__process_resources.d --android-sdk-jar ../../third_party/android_tools/sdk/platforms/android-23/android.jar --aapt-path ../../third_party/android_tools/sdk/build-tools/23.0.1/aapt --android-manifest ../../build/android/AndroidManifest.xml --resource-dirs=\[\"../../components/web_contents_delegate_android/android/java/res\"\] --srcjar-out gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.srcjar --resource-zip-out gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.resources.zip --r-text-out gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources_R.txt --dependencies-res-zips=@FileArg\(gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.build_config:resources:dependency_zips\) --extra-res-packages=@FileArg\(gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.build_config:resources:extra_package_names\) --extra-r-text-files=@FileArg\(gen/components/web_contents_delegate_android/web_contents_delegate_android_java_resources.build_config:resources:extra_r_text_files\) --non-constant-id --custom-package org.chromium.components.web_contents_delegate_android --shared-resources
> Traceback (most recent call last):
>   File "../../build/android/gyp/process_resources.py", line 541, in <module>
>     main(sys.argv[1:])
>   File "../../build/android/gyp/process_resources.py", line 537, in main
>     force=options.R_dir)
>   File "/mnt/f/Crosswalk/src/build/android/gyp/util/build_utils.py", line 527, in CallAndWriteDepfileIfStale
>     pass_changes=True)
>   File "/mnt/f/Crosswalk/src/build/android/gyp/util/md5_check.py", line 87, in CallAndRecordIfStale
>     function(*args)
>   File "/mnt/f/Crosswalk/src/build/android/gyp/util/build_utils.py", line 511, in on_stale_md5
>     function(*args)
>   File "../../build/android/gyp/process_resources.py", line 531, in <lambda>
>     lambda: _OnStaleMd5(options),
>   File "../../build/android/gyp/process_resources.py", line 428, in _OnStaleMd5
>     build_utils.CheckOutput(package_command, print_stderr=False)
>   File "/mnt/f/Crosswalk/src/build/android/gyp/util/build_utils.py", line 164, in CheckOutput
>     stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 8] Exec format error
> [1935/17278] ACTION //components/resources:about_credits(//build/toolchain/android:arm)
> ninja: build stopped: subcommand failed.

**Comment by rakuco** [comment]
> OSError: [Errno 8] Exec format error

My first guess it that you're on a 64-bit host and have not installed all the packages required to run 32-bit binaries there. Are you able to run all the Android SDK tools without issues?

**Comment by frankvdb7** [comment]
> My first guess it that you're on a 64-bit host and have not installed all the packages required to run 32-bit binaries there. Are you able to run all the Android SDK tools without issues?

I was using 64-bit Ubuntu which out-of-the-box does not support 32-bit libraries. I (for the time being) manually replaced the Android SDK platform-tools and build-tools (25.0.2) and now the build is working. However, this is just a temporary solution... The Android SDK should really be updated to the latest version that is 64-bit only.

**Comment by rakuco** [comment]
Unfortunately I'm afraid that's not going to happen, as we're tied to whatever version of the SDK was shipped with the Chromium release we were using at the time Crosswalk stopped being maintained.

**Comment by frankvdb7** [comment]
Is it possible to update the Chromium release used by Crosswalk in my local repository? (by myself) Is there any documentation I can use?

**Comment by rakuco** [comment]
Not without [major effort](https://github.com/crosswalk-project/crosswalk-website/wiki/Rebasing-our-forks).

**Comment by fengcai** [comment]
I am on Ubuntu 16.04 LTS x86_64 and run into the same issue, but I can't find answer, how to solve it?
or what 32 bit packages should I have to install?

thanks
