### ISSUE TITLE
can't load crosswalk from maven

### ISSUE THREAD

**Issue by sandlz** [crosswalk-project/crosswalk#4010]
The maven address `https://download.01.org/crosswalk/releases/crosswalk/` is down

**Comment by beevelop** [comment]
Same here. The service responds with 503 Service unavailable.
```
> GET /crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml HTTP/1.1
> Host: download.01.org
< HTTP/1.1 503 Service Unavailable
< Server: AkamaiGHost
```

Maven exception for people coming from Google:
```
> Could not resolve org.xwalk:xwalk_core_library:23+.
   > Failed to list versions for org.xwalk:xwalk_core_library.
      > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
         > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable
```

**Comment by dbeylkhanov** [comment]
@rakuco @lpereira @darktears 
![image](https://user-images.githubusercontent.com/7656847/29998116-51a9f038-902b-11e7-82f7-0be45a51c964.png)

**Comment by curtis2** [comment]
so. Any response from crosswalk official for this  issue?

**Comment by sandlz** [comment]
check this. @curtis2 
https://stackoverflow.com/questions/46012838/ionic-3-project-and-plugin-crosswalk-error

**Comment by knvpk** [comment]
I too got his error.
![crosswalk_error](https://user-images.githubusercontent.com/6078669/30014126-2eaf784e-9168-11e7-8ae9-69bf57dcabc8.png)

**Comment by rakuco** [comment]
Thanks for the report. There are many duplicate reports about this, so let's centralize them in crosswalk-project/cordova-plugin-crosswalk-webview#158
