### ISSUE TITLE
How to Enable-Experimental-WebPlatform-Features

### ISSUE THREAD

**Issue by Gaubee** [crosswalk-project/crosswalk#4015]
I want to use `backdrop-filter` css property, but it only work on safari.
in chromium, this feature will enable when use chromium flags: --enable-experimental-web-platform-features. I don't know how to use this in crosswalk, please help.

**Comment by Gaubee** [comment]
I use cordova. I change the variable of the **cordova-plugin-crosswalk-webview** plugin in config.xml:
```xml
<variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect --enable-experimental-web-platform-features" />
```
but when I run `cordova build android` , the config will be overwrite back to:
```xml
 <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
```

----

And then , I force rewrite this file `%PROJECT%/platforms/android/cordova-plugin-crosswalk-webview/bnlc-xwalk.gradle` 
```gradle
ext.xwalkCommandLine = getConfigPreference("xwalkCommandLine")+' --enable-experimental-web-platform-features'
```

finally it work for me.

----

Now I think This is an bug.

**Comment by Gaubee** [comment]
Oh, My wrong, I should do this:
```shell
cordova plugin add cordova-plugin-crosswalk-webview  --variable XWALK_COMMANDLINE="--disable-pull-to-refresh-effect --enable-experimental-web-platform-features"
```

**Comment by erickvieira** [comment]
Can you give more details about your project setup? It didn't work for me, anyway. Whats your cordova version, for example?

From my **config.xml**:

    <plugin name="cordova-plugin-crosswalk-webview" spec="2.4.0">  
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect --enable-experimental-web-platform-features" />  
        <variable name="XWALK_VERSION" value="23+" />  
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />  
        <variable name="XWALK_MODE" value="embedded" />  
        <variable name="XWALK_MULTIPLEAPK" value="true" />  
    </plugin>

**Comment by d410** [comment]
Did you ever enable this flag on a cordova project?
