### ISSUE TITLE
Upgrading Chromium

### ISSUE THREAD

**Issue by hariszukanovic** [crosswalk-project/crosswalk#4018]
How difficult would you rate upgrading the current crosswalk to the current chromium version?
Is there a (good and usable) guide on how to do that?

**Comment by rakuco** [comment]
> How difficult would you rate upgrading the current crosswalk to the current chromium version?

Quite difficult, Crosswalk has been unmaintained for almost a year and it's lagging behind Chromium's releases by about 10 releases now. See also: #4001.

> Is there a (good and usable) guide on how to do that?

This is what we used to follow: https://github.com/crosswalk-project/crosswalk-website/wiki/Rebasing-our-forks
