### ISSUE TITLE
Unable to find attribute android:fontVariationSettings

### ISSUE THREAD

**Issue by luzeeker** [crosswalk-project/crosswalk#4025]
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Marchhill** [comment]
See this https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205

**Comment by rakuco** [comment]
Closing as a duplicate of the issue above.
