### ISSUE TITLE
Maven Repo / Website / Mailing List is Down (2019)

### ISSUE THREAD

**Issue by nappy** [crosswalk-project/crosswalk#4042]
The maven repo at https://download.01.org/crosswalk/releases/crosswalk/ seems to be offline.

Maybe someone could be so kind and look into this.

**Comment by soypaduano** [comment]
same here

**Comment by 349989153** [comment]
same here

**Comment by ath0mas** [comment]
the whole **Intel Open Source Technology Center: 01.org** https://01.org/ is down, ping @01org
(tracked in [reddit](https://www.reddit.com/r/linux/comments/ajau5e/intel_open_source_technology_center_01org_down/) too)

**Comment by ath0mas** [comment]
seems to be back to normal 🆙

**Comment by soypaduano** [comment]
yup, everything working :-)

**Comment by rakuco** [comment]
Everything's been working fine for 22 days now, so I'm closing this issue.
